apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: beta
spec:
  selector:
    app: go
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31001
  type: LoadBalancer
