apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
  namespace: beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-service
  template:
    metadata:
      labels:
        app: go-service
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - image: registry.gitlab.com/bunlert274/go-service:latest
          imagePullPolicy: Always
          name: go-service
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
